videoGames = `[
    {
        "date": "2024-03-15T00:00:00",
        "name": "Red Dead Redemption 2",
        "developer": "Rockstar Games",
        "publisher": "Rockstar Games",
        "platform": "Steam",
        "price": 29.56,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2024-01-26T00:00:00",
        "name": "Slay the Spire",
        "developer": "Mega Crit",
        "publisher": "Humble Bundle",
        "platform": "Steam",
        "price": 12.17,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-12-27T00:00:00",
        "name": "Dredge",
        "developer": "Black Salt Games",
        "publisher": "Team17",
        "platform": "Steam",
        "price": 27.29,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-10-21T00:00:00",
        "name": "Super Mario Bros. Wonder",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-10-06T00:00:00",
        "name": "Elden Ring",
        "developer": "FromSoftware, Inc.",
        "publisher": "Bandai Namco Entertainment",
        "platform": "Steam",
        "price": 59.12,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-09-08T00:00:00",
        "name": "Noita",
        "developer": "Nolla Games",
        "publisher": "Nolla Games",
        "platform": "Steam",
        "price": 25.52,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-07-08T00:00:00",
        "name": "Uncharted: Legacy of Thieves Collection",
        "developer": "Naughty Dog",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Steam",
        "price": 43.67,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-06-24T00:00:00",
        "name": "Inscryption",
        "developer": "Daniel Mullins Games",
        "publisher": "Devolver Digital",
        "platform": "Steam",
        "price": 15.31,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-05-12T00:00:00",
        "name": "The Legend of Zelda: Tears of the Kingdom",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 94.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-04-22T00:00:00",
        "name": "Vampire Survivors",
        "developer": "Luca Galante",
        "publisher": "Luca Galante",
        "platform": "Steam",
        "price": 5.36,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-04-07T00:00:00",
        "name": "Death's Door",
        "developer": "Acid Nerve",
        "publisher": "Devolver Digital",
        "platform": "Steam",
        "price": 29.11,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-02-23T00:00:00",
        "name": "No Man's Sky",
        "developer": "Hello Games",
        "publisher": "Hello Games",
        "platform": "Steam",
        "price": 28.59,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2023-01-01T00:00:00",
        "name": "Spider-Man Remastered",
        "developer": "Insomniac Games",
        "publisher": "PlayStation Studios",
        "platform": "Steam",
        "price": 52.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-12-22T00:00:00",
        "name": "Untitled Goose Game",
        "developer": "House House",
        "publisher": "Panic Inc.",
        "platform": "Steam",
        "price": 12.76,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-12-12T00:00:00",
        "name": "Metal Gear Solid V: The Phantom Pain",
        "developer": "Konami",
        "publisher": "Konami",
        "platform": "Steam",
        "price": 4.85,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-12-02T00:00:00",
        "name": "Steam Deck",
        "developer": "",
        "publisher": "Valve",
        "platform": "Steam",
        "price": 558.88,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 1
    },
    {
        "date": "2022-12-01T00:00:00",
        "name": "Xbox Game Pass For PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-11-01T00:00:00",
        "name": "Xbox Game Pass For PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-09-30T00:00:00",
        "name": "Xbox Game Pass For PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-08-29T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 1.12,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-07-03T00:00:00",
        "name": "Middle-earth: Shadow of War",
        "developer": "Monolith Productions",
        "publisher": "Warner Bros Interactive Entertainment",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-06-15T00:00:00",
        "name": "Nintendo Switch Online",
        "developer": "",
        "publisher": "",
        "platform": "Switch",
        "price": 5.49,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-05-21T00:00:00",
        "name": "Rogue Legacy 2",
        "developer": "Cellar Door Games",
        "publisher": "Cellar Door Games",
        "platform": "Epic Games Store",
        "price": 18.8,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-05-01T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-04-07T00:00:00",
        "name": "Mario Kart 8 Deluxe - Booster Course Pack",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 34.64,
        "is_dlc": 1,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-04-01T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-02-28T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-02-28T00:00:00",
        "name": "Mario Kart 8 Deluxe",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 89.59,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2022-02-01T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2022-01-01T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2021-12-01T00:00:00",
        "name": "Halo Infinite Premium Battle Pass",
        "developer": "343 Industries",
        "publisher": "Xbox Game Studios",
        "platform": "Microsoft Store",
        "price": 13.09,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-11-30T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2021-10-30T00:00:00",
        "name": "The Legend of Zelda: Link's Awakening",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 50,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-10-29T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 1.12,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2021-10-21T00:00:00",
        "name": "Resident Evil 4",
        "developer": "Armature Studio",
        "publisher": "Oculus",
        "platform": "Quest 2",
        "price": 48.29,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-09-17T00:00:00",
        "name": "Deathloop",
        "developer": "Arkane Studios",
        "publisher": "Bethesda Softworks",
        "platform": "Steam",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-07-06T00:00:00",
        "name": "Hades",
        "developer": "Supergiant Games",
        "publisher": "Supergiant Games",
        "platform": "Steam",
        "price": 21.3,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-06-12T00:00:00",
        "name": "Prey",
        "developer": "Arkane Studios",
        "publisher": "Bethesda Softworks",
        "platform": "Steam",
        "price": 20.89,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-05-14T00:00:00",
        "name": "Myst",
        "developer": "Cyan Worlds, Inc",
        "publisher": "Cyan Worlds, Inc",
        "platform": "Quest 2",
        "price": 34.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-04-12T00:00:00",
        "name": "Deus Ex: Mankind Divided",
        "developer": "Eidos-Montréal",
        "publisher": "Square Enix",
        "platform": "Steam",
        "price": 5.32,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-03-06T00:00:00",
        "name": "Keep Talking and Nobody Explodes",
        "developer": "Steel Crate Games",
        "publisher": "Steel Crate Games",
        "platform": "Quest 2",
        "price": 16.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-02-24T00:00:00",
        "name": "Valheim",
        "developer": "Iron Gate Studio",
        "publisher": "Coffee Stain Studios",
        "platform": "Steam",
        "price": 22.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-02-13T00:00:00",
        "name": "Ratchet & Clank",
        "developer": "Insomniac Games",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 22.38,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-01-30T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 1.12,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2021-01-23T00:00:00",
        "name": "A Fisherman's Tale",
        "developer": "Innerspace Vr",
        "publisher": "Vertigo Games",
        "platform": "Quest 2",
        "price": 11.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-01-20T00:00:00",
        "name": "Cribbage with Grandpas",
        "developer": "Less Than Three Interactive",
        "publisher": "Less Than Three Interactive",
        "platform": "App Store",
        "price": 4.47,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-01-01T00:00:00",
        "name": "Star Wars Battlefront II",
        "developer": "Criterion Games",
        "publisher": "Electronic Arts",
        "platform": "Steam",
        "price": 9.38,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-01-01T00:00:00",
        "name": "Star Wars Jedi: Fallen Order",
        "developer": "Respawn Entertainment",
        "publisher": "Electronic Arts",
        "platform": "Steam",
        "price": 29.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2021-01-01T00:00:00",
        "name": "Star Wars: Squadrons",
        "developer": "Motive Studios",
        "publisher": "Electronic Arts",
        "platform": "Steam VR",
        "price": 26.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-12-22T00:00:00",
        "name": "Half Life: Alyx",
        "developer": "Valve",
        "publisher": "Valve",
        "platform": "Steam VR",
        "price": 51.74,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-12-13T00:00:00",
        "name": "Moss",
        "developer": "Polyarc",
        "publisher": "Polyarc",
        "platform": "Quest 2",
        "price": 34.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-12-07T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-12-06T00:00:00",
        "name": "The Room VR: A Dark Matter",
        "developer": "Fireproof Studios",
        "publisher": "Fireproof Studios",
        "platform": "Quest 2",
        "price": 26.24,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-30T00:00:00",
        "name": "Robo Recall: Unplugged",
        "developer": "Epic Games",
        "publisher": "Epic Games",
        "platform": "Quest 2",
        "price": 34.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-27T00:00:00",
        "name": "Quest 2",
        "developer": "",
        "publisher": "Oculus",
        "platform": "Quest 2",
        "price": 448.21,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 1
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "A-Tech Cybernetic",
        "developer": "XREAL Games",
        "publisher": "XREAL Games",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "Archangel: Hellfire - Fully Loaded",
        "developer": "Skydance Interactive",
        "publisher": "Skydance Interactive",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "Creed: Rise to Glory",
        "developer": "Survios",
        "publisher": "Survios",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "I Expect You To Die",
        "developer": "Schell Games",
        "publisher": "Schell Games",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "Killing Floor Incusion",
        "developer": "Tripwire Interactive, LLC",
        "publisher": "Tripwire Interactive, LLC",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "Raw Data",
        "developer": "Survios",
        "publisher": "Survios",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "The Walking Dead: Saints & Sinners",
        "developer": "Skydance Interactive",
        "publisher": "Skydance Interactive",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-14T00:00:00",
        "name": "Zero Caliber VR",
        "developer": "XREAL Games",
        "publisher": "XREAL Games",
        "platform": "Steam VR",
        "price": 2.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-11-07T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 13.43,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-10-07T00:00:00",
        "name": "Playstation Now",
        "developer": "",
        "publisher": "",
        "platform": "Playstation 4",
        "price": 12.99,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-09-29T00:00:00",
        "name": "Spelunky 2",
        "developer": "Mossmouth",
        "publisher": "Mossmouth",
        "platform": "Steam",
        "price": 20.51,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-09-07T00:00:00",
        "name": "Xbox Game Pass for PC",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 6.71,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-08-07T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 1,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-08-04T00:00:00",
        "name": "Carrion",
        "developer": "Phobia Game Studio",
        "publisher": "Devolver Digital",
        "platform": "Steam",
        "price": 22.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-07-04T00:00:00",
        "name": "Apple Arcade",
        "developer": "",
        "publisher": "",
        "platform": "App Store",
        "price": 6.71,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2020-06-17T00:00:00",
        "name": "The Last of Us Part II",
        "developer": "Naughty Dog",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 79.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-05-20T00:00:00",
        "name": "Animal Crossing: New Horizons",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-04-11T00:00:00",
        "name": "Jackbox Party Pack 5",
        "developer": "Jackbox Games",
        "publisher": "Jackbox Games",
        "platform": "Steam",
        "price": 33.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-04-05T00:00:00",
        "name": "Control",
        "developer": "Remedy Entertainment",
        "publisher": "505 Games",
        "platform": "Epic Games Store",
        "price": 42.73,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-03-20T00:00:00",
        "name": "Doom Eternal",
        "developer": "id Software",
        "publisher": "Bethesda Softworks",
        "platform": "Bethesda Launcher",
        "price": 69.59,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-02-24T00:00:00",
        "name": "Titanfall 2",
        "developer": "Respawn Entertainment",
        "publisher": "Electronic Arts",
        "platform": "Origin",
        "price": 6.81,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2020-01-04T00:00:00",
        "name": "Luigi's Mansion 3",
        "developer": "Next Level Games, Inc.",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-12-25T00:00:00",
        "name": "Resident Evil 2: Remake",
        "developer": "Capcom",
        "publisher": "Capcom",
        "platform": "Steam",
        "price": 19.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-12-23T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 19.03,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2019-09-08T00:00:00",
        "name": "Xbox Game Pass Ultimate",
        "developer": "",
        "publisher": "",
        "platform": "Microsoft Store",
        "price": 2,
        "is_dlc": 0,
        "is_subscription": 1,
        "is_console": 0
    },
    {
        "date": "2019-09-02T00:00:00",
        "name": "Tom Clancy's Ghost Recon: Wildlands",
        "developer": "Ubisoft Paris",
        "publisher": "Ubisoft",
        "platform": "Epic Games Store",
        "price": 23.31,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-07-24T00:00:00",
        "name": "Doom",
        "developer": "id Software",
        "publisher": "Bethesda Softworks",
        "platform": "Steam",
        "price": 6.66,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-06-23T00:00:00",
        "name": "Super Mario Maker 2",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 87.82,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-06-16T00:00:00",
        "name": "Overcooked! 2",
        "developer": "Ghost Town Games",
        "publisher": "Team17 Software Limited",
        "platform": "GOG Galaxy",
        "price": 20.29,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-06-09T00:00:00",
        "name": "Void Bastards",
        "developer": "Blue Manchu",
        "publisher": "Humble Games",
        "platform": "Steam",
        "price": 39.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-06-01T00:00:00",
        "name": "Broken Age",
        "developer": "Double Fine Productions, Inc.",
        "publisher": "Double Fine Productions, Inc.",
        "platform": "Play Store",
        "price": 6.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-04-13T00:00:00",
        "name": "Fallout 4: Game of the Year Edition",
        "developer": "Bethesda Softworks",
        "publisher": "Bethesda Softworks",
        "platform": "Steam",
        "price": 21.69,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-03-26T00:00:00",
        "name": "Baba is You",
        "developer": "Hempuli Oy",
        "publisher": "Hempuli Oy",
        "platform": "Switch",
        "price": 19.85,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-03-11T00:00:00",
        "name": "Return of the Obra Dinn",
        "developer": "Lucas Pope",
        "publisher": "Lucas Pope",
        "platform": "GOG Galaxy",
        "price": 22.79,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-01-11T00:00:00",
        "name": "Cribbage with Grandpas",
        "developer": "Less Than Three Interactive",
        "publisher": "Less Than Three Interactive",
        "platform": "Play Store",
        "price": 3.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2019-01-06T00:00:00",
        "name": "Call of Duty: Black Ops 4",
        "developer": "Treyarch",
        "publisher": "Activision",
        "platform": "Battle.net",
        "price": 41.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-12-25T00:00:00",
        "name": "Hitman 2",
        "developer": "IO Interactive",
        "publisher": "Warner Bros Interactive Entertainment",
        "platform": "Steam",
        "price": 50.39,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-12-09T00:00:00",
        "name": "Super Smash Bros. Ultimate",
        "developer": "Bandai Namco Entertainment",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-11-08T00:00:00",
        "name": "Red Dead Redemption 2",
        "developer": "Rockstar",
        "publisher": "Rockstar",
        "platform": "Playstation 4",
        "price": 79.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-11-07T00:00:00",
        "name": "Reigns",
        "developer": "Nerial",
        "publisher": "Devolver Digital",
        "platform": "Play Store",
        "price": 3.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-09-13T00:00:00",
        "name": "Destiny 2",
        "developer": "Bungie",
        "publisher": "Activision",
        "platform": "Battle.net",
        "price": 79.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-09-03T00:00:00",
        "name": "Flinthook",
        "developer": "Tribute Games",
        "publisher": "Tribute Games",
        "platform": "Switch",
        "price": 18.83,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-08-25T00:00:00",
        "name": "Captain Toad: Treasure Tracker",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 55.37,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-08-17T00:00:00",
        "name": "Holedown",
        "developer": "webbfarbror AB",
        "publisher": "webbfarbror AB",
        "platform": "Play Store",
        "price": 5.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-07-24T00:00:00",
        "name": "Forza Horizon 3",
        "developer": "Playground Games",
        "publisher": "Xbox Game Studios",
        "platform": "Xbox One",
        "price": 53.1,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-07-21T00:00:00",
        "name": "Ridiculous Fishing",
        "developer": "Vlambeer",
        "publisher": "Vlambeer",
        "platform": "Play Store",
        "price": 3.29,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-07-07T00:00:00",
        "name": "Diablo 3: Rise of the Necromancer",
        "developer": "Blizzard Entertainment",
        "publisher": "Blizzard Entertainment",
        "platform": "Battle.net",
        "price": 18.99,
        "is_dlc": 1,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-06-17T00:00:00",
        "name": "Dragonborn",
        "developer": "Bethesda Softworks",
        "publisher": "Bethesda Softworks",
        "platform": "Steam",
        "price": 12.02,
        "is_dlc": 1,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-06-08T00:00:00",
        "name": "God of War",
        "developer": "Santa Monica Studio",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 66.39,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-04-12T00:00:00",
        "name": "Ni No Kuni II: Revenant Kingdom",
        "developer": "Level-5 Inc.",
        "publisher": "Bandai Namco Entertainment",
        "platform": "Playstation 4",
        "price": 79.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-04-06T00:00:00",
        "name": "Bridge Constructor Portal",
        "developer": "ClockStone",
        "publisher": "Headup Games",
        "platform": "Play Store",
        "price": 6.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-02-28T00:00:00",
        "name": "Into The Breach",
        "developer": "Subset Games",
        "publisher": "Subset Games",
        "platform": "Steam",
        "price": 17.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-02-19T00:00:00",
        "name": "Gerrymander: Rig the System",
        "developer": "Good Egg Games",
        "publisher": "Good Egg Games",
        "platform": "Play Store",
        "price": 2.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-01-29T00:00:00",
        "name": "Assassin's Creed Origins",
        "developer": "Ubisoft Montreal",
        "publisher": "Ubisoft",
        "platform": "Xbox One",
        "price": 47.86,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-01-28T00:00:00",
        "name": "Far Cry 2",
        "developer": "Ubisoft Montreal",
        "publisher": "Ubisoft",
        "platform": "Steam",
        "price": 2.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2018-01-28T00:00:00",
        "name": "Universal Paperclips",
        "developer": "Frank Lantz",
        "publisher": "Frank Lantz",
        "platform": "Play Store",
        "price": 2.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-12-28T00:00:00",
        "name": "Uncharted: The Lost Legacy",
        "developer": "Naughty Dog",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 25.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-12-19T00:00:00",
        "name": "SteamWorld Dig 2",
        "developer": "Image & Form",
        "publisher": "Image & Form",
        "platform": "Switch",
        "price": 20.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-12-15T00:00:00",
        "name": "Puzzle Fighter gem pack",
        "developer": "",
        "publisher": "",
        "platform": "Play Store",
        "price": 6.99,
        "is_dlc": 1,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-11-21T00:00:00",
        "name": "Prey",
        "developer": "Arkane Studios",
        "publisher": "Bethesda Softworks",
        "platform": "Xbox One",
        "price": 28.25,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-10-25T00:00:00",
        "name": "Super Mario Odyssey",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-09-30T00:00:00",
        "name": "Cuphead",
        "developer": "Studio MDHR",
        "publisher": "Studio MDHR",
        "platform": "Xbox One",
        "price": 29.37,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-08-22T00:00:00",
        "name": "Destiny 2",
        "developer": "Bungie",
        "publisher": "Activision",
        "platform": "Xbox One",
        "price": 146.89,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-08-21T00:00:00",
        "name": "Facility 47",
        "developer": "Inertia Game Studio",
        "publisher": "Inertia Game Studio",
        "platform": "Play Store",
        "price": 4.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-08-05T00:00:00",
        "name": "Skyshine's BEDLAM Redux!",
        "developer": "",
        "publisher": "",
        "platform": "GOG.com",
        "price": 4.09,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-08-05T00:00:00",
        "name": "No Man's Sky",
        "developer": "Hello Games",
        "publisher": "Hello Games",
        "platform": "Playstation 4",
        "price": 39.54,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-07-13T00:00:00",
        "name": "Splatoon 2",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 83.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-06-30T00:00:00",
        "name": "Mini Metro",
        "developer": "Dinosaur Polo Club",
        "publisher": "Dinosaur Polo Club",
        "platform": "Play Store",
        "price": 1.29,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-06-15T00:00:00",
        "name": "Wolfenstein: The New Order",
        "developer": "MachineGames",
        "publisher": "Bethesda Softworks",
        "platform": "Playstation 4",
        "price": 16.19,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-06-07T00:00:00",
        "name": "Watch Dogs 2",
        "developer": "Ubisoft Montreal",
        "publisher": "Ubisoft",
        "platform": "Playstation 4",
        "price": 33.59,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-05-29T00:00:00",
        "name": "Dead Cells",
        "developer": "Motion Twin",
        "publisher": "Motion Twin",
        "platform": "Steam",
        "price": 18.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-05-05T00:00:00",
        "name": "Darkest Dungeon",
        "developer": "Red Hook Studios",
        "publisher": "Red Hook Studios",
        "platform": "Playstation Vita",
        "price": 33.49,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-04-23T00:00:00",
        "name": "Horizon Zero Dawn",
        "developer": "Guerrilla Games",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 79.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-04-11T00:00:00",
        "name": "Catherine",
        "developer": "Atlus Co. Ltd.",
        "publisher": "Atlus Co. Ltd.",
        "platform": "Xbox 360",
        "price": 3.38,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-03-22T00:00:00",
        "name": "Snipperclips: Cut It Out, Together!",
        "developer": "SFB Games",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 29.6,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-03-03T00:00:00",
        "name": "Switch",
        "developer": "",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 451.95,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 1
    },
    {
        "date": "2017-03-03T00:00:00",
        "name": "The Legend of Zelda: Breath of the Wild",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "platform": "Switch",
        "price": 90.35,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-02-02T00:00:00",
        "name": "Hitman Upgrade Pack",
        "developer": "IO Interactive",
        "publisher": "Square Enix",
        "platform": "Playstation 4",
        "price": 59.99,
        "is_dlc": 1,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-19T00:00:00",
        "name": "Hitman",
        "developer": "IO Interactive",
        "publisher": "Square Enix",
        "platform": "Playstation 4",
        "price": 17.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-19T00:00:00",
        "name": "Party Hard",
        "developer": "",
        "publisher": "",
        "platform": "Playstation 4",
        "price": 12.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-18T00:00:00",
        "name": "Solitairica",
        "developer": "Righteous Hammer Games",
        "publisher": "Righteous Hammer Games",
        "platform": "Play Store",
        "price": 4.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-16T00:00:00",
        "name": "Bloodborne",
        "developer": "FromSoftware, Inc.",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 29.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-15T00:00:00",
        "name": "Nonogram Survival",
        "developer": "",
        "publisher": "",
        "platform": "Play Store",
        "price": 4.09,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-14T00:00:00",
        "name": "The Witness",
        "publisher": "Thekla, Inc",
        "developer": "Thekla, Inc",
        "platform": "Playstation 4",
        "price": 39.99,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    },
    {
        "date": "2017-01-08T00:00:00",
        "name": "Playstation 4 Slim",
        "developer": "",
        "publisher": "Sony",
        "platform": "Playstation 4",
        "price": 337.36,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 1
    },
    {
        "date": "2017-01-08T00:00:00",
        "name": "Uncharted 4: A Thief's End",
        "developer": "Naughty Dog",
        "publisher": "Sony Interactive Entertainment",
        "platform": "Playstation 4",
        "price": 40,
        "is_dlc": 0,
        "is_subscription": 0,
        "is_console": 0
    }
]`;
